name: IndexNow Action

on:
  push:
    branches:
      - main

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: IndexNow Action
        uses: bojieyang/indexnow-action@v3.0.0
        with:
          sitemap-location: 'https://www.africanphotosandvideos.com.ng/sitemap.xml'
          key: ${{ stocksite2026.INDEXNOW_KEY }}
